### ISSUE TITLE
filter does not exist

### ISSUE THREAD

**Issue by ghost** [victorhaggqvist/Twig-sort-by-field#11]
![snilius1](https://user-images.githubusercontent.com/8593884/27408795-07c2b006-56a4-11e7-94e2-907fad3c3e03.png)
![snilius2](https://user-images.githubusercontent.com/8593884/27408796-07d0238a-56a4-11e7-805b-5214c64e74e7.png)

Any idea what is causing this error? Iv moved the composer related files to the server. And I have moved the vendor folder to the server. 

But the error remains. 

Am I missing a step in the process?

**Comment by deltab** [comment]
Have you registered the extension with Twig? For instance, if you're using Symfony:

<blockquote>
For Symfony usage you'll want to add it as a service and tag it for Twig.

```yml
# app/config/services.yml
services:
    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }
```
</blockquote>
